services:
  # The Search Engine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limits RAM usage
    volumes:
      - es_data:/usr/share/elasticsearch/data  # Persists search index even if container is deleted
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Flask App
  web:
    build: .
    container_name: flask_app
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SQLALCHEMY_DATABASE_URI=sqlite:///site.db
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=1
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      elasticsearch:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  worker:
    build: .
    command: tasktiger -h redis
    env_file: .env
    volumes:
      - .:/app
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - DATABASE_URL=sqlite:///site.db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_HOST=redis
      - PYTHONPATH=/app
    depends_on:
      - redis
      - elasticsearch

volumes:
  es_data:  # Defines the named volume for search persistence